spring:
  # rabbitmq消息总线连接信息
  rabbitmq:
    addresses: 192.168.50.115:5672
    username: user
    password: password

zuul:
  routes:
    # 将/product/** 重定向 /myProduct/**
    product:
      path: /myProduct/**
      serviceId: product
      # 关闭请求头的过滤
      sensitiveHeaders:
    # 将/order-client/** 重定向 /order/**
   # order-client: /order/**
  # 指定接口,不提供给外部访问
  ignored-patterns:
    - /**/product/listForOrder
  # 指定禁止外部访问的微服务
  ignored-services:
